services:
  # 后端项目
  server:
    container_name: server
    build: docker/
    hostname: server-thrive
    ports:
      - "9003:9003"
    networks:
      thrive_network:
        ipv4_address: 172.178.178.14
    environment:
      ## 设置数据库主机地址
      DB_INFO: DbHost:Port3306/DbNameThriveX
      ## 设置数据库名,强烈建议修改(首次启动有效)-必须和前面的数据库名一致
      DB_NAME: DbNameThriveX
      ## 设置数据库用户名,强烈建议修改(首次启动有效)-必须和前面的数据库用户名一致
      DB_USERNAME: DbUserThrive
      ## 设置数据库密码,强烈建议修改(首次启动有效)-必须和前面的数据库用户名一致
      DB_PASSWORD: DB_PASSWORD_ThriveX@123?
      ## 设置数据库端口
      DB_PORT: Port3306
      ## 设置邮箱配置
      EMAIL_HOST: smtp.qq.com
      ## 设置邮箱端口
      EMAIL_PORT: 465
      ## 设置邮箱用户名
      EMAIL_USERNAME: 123456789@qq.com
      ## 设置邮箱密码
      EMAIL_PASSWORD: 123456789Password

# 网络配置
networks:
  thrive_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.178.178.0/24